ALTER TABLE matches ADD COLUMN IF NOT EXISTS rationale TEXT;

ALTER TABLE analyses ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'COMPLETED';

ALTER TABLE recommendations ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'COMPLETED';
