services:
  postgres:
    image: postgres:16-alpine
    container_name: matchiq-postgres
    environment:
      POSTGRES_DB: matchiq_dev
      POSTGRES_USER: matchiq_admin
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - matchiq_postgres_data:/var/lib/postgresql/data
    networks:
      - matchiq-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: matchiq-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@matchiq.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - matchiq-network

volumes:
  matchiq_postgres_data:

networks:
  matchiq-network:
    driver: bridge

